# Generated by Django 6.0.4 on 2026-05-07 17:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birth_date_user_sex_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_card',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.identity_card_field_path),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.national_card_field_path),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.resume_field_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_field_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1, null=True),
        ),
    ]
