# Generated by Django 6.0.4 on 2026-05-07 21:12

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_identity_card_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.CreateModel(
            name='InstructorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10)),
                ('national_card', models.ImageField(blank=True, null=True, upload_to=users.models.national_card_field_path)),
                ('identity_card', models.ImageField(blank=True, null=True, upload_to=users.models.identity_card_field_path)),
                ('resume', models.FileField(upload_to=users.models.resume_field_path)),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('R', 'regected')], default='P', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
