# Generated by Django 6.0.4 on 2026-05-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_instructorverification_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorverification',
            name='reviewed_at',
            field=models.DateTimeField(),
        ),
    ]
