version: '3.8'

services:
  backend:
    build: ./backend/code-learn-back
    ports:
      - "8000:8000"
    volumes:
      - ./backend/code-learn-back:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules