# Generated by Django 6.0.4 on 2026-05-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
