# Generated by Django 6.0.4 on 2026-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='final price after discount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='percent of discount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DR', 'draft'), ('PE', 'pending'), ('PU', 'published'), ('AR', 'archived')], default='DR', max_length=2),
        ),
    ]
