# Generated by Django 6.0.4 on 2026-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_is_free_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='final price after discount'),
        ),
    ]
