# Generated by Django 6.0.4 on 2026-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_identity_card_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorverification',
            name='national_code',
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
