# Generated by Django 6.0.4 on 2026-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_instructorverification_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
